import { shortId } from './format';
import type {
  ConnectionState,
  DaemonErrorShape,
  DaemonStatus,
  FileEntry,
  Member,
  PeerStatus,
  PipeEntry,
  RoomSummary,
} from './protocol';

export interface DiagnosticEvent {
  context: string;
  code: string;
  message: string;
  hint: string | null;
  at: string;
}

type FetchLike = {
  phase: string;
  error?: DaemonErrorShape;
};

export interface DiagnosticsInput {
  generatedAt: string;
  uiVersion: string;
  browser: string;
  platform: string;
  transport: string;
  connection: ConnectionState;
  status: DaemonStatus | null;
  rooms: RoomSummary[];
  currentRoomId: string | null;
  members: Member[];
  files: FileEntry[];
  fetches: Record<string, FetchLike>;
  pipes: PipeEntry[];
  peers: PeerStatus[];
  lastError: DiagnosticEvent | null;
}

function countBy<T>(items: T[], keyFor: (item: T) => string | null | undefined): Record<string, number> {
  return items.reduce<Record<string, number>>((counts, item) => {
    const key = keyFor(item) ?? 'unknown';
    counts[key] = (counts[key] ?? 0) + 1;
    return counts;
  }, {});
}

function countRecordValues(record: Record<string, number>): string {
  const entries = Object.entries(record).sort(([a], [b]) => a.localeCompare(b));
  if (entries.length === 0) return 'none';
  return entries.map(([key, value]) => `${key}=${value}`).join(', ');
}

function redact(value: string): string {
  return value
    .replace(/roomtkt1[0-9a-z]+/gi, '<ticket>')
    .replace(/[a-z0-9]{20,}@[^\s'")]+/gi, '<endpoint-address>')
    .replace(/[A-Fa-f0-9]{64}/g, '<hash>')
    .replace(/\/(?:Users|home|tmp|var|private|Volumes)\/[^\s'")]+/g, '<local-path>')
    .replace(/[A-Za-z]:\\[^\s'")]+/g, '<local-path>');
}

function shortOrNone(id: string | null | undefined): string {
  return id ? shortId(id) : 'none';
}

function currentRoom(input: DiagnosticsInput): RoomSummary | null {
  if (!input.currentRoomId) return null;
  return input.rooms.find((room) => room.room_id === input.currentRoomId) ?? null;
}

export function buildDiagnostics(input: DiagnosticsInput): string {
  const current = currentRoom(input);
  const fetchPhases = countBy(Object.values(input.fetches), (fetch) => fetch.phase);
  const fetchErrors = Object.values(input.fetches)
    .filter((fetch) => fetch.phase === 'error')
    .map((fetch) => fetch.error?.code ?? 'unknown');
  const filesFetched = input.files.filter(
    (file) => file.fetched || ['fetched', 'verified'].includes(input.fetches[file.file_id]?.phase ?? ''),
  ).length;
  const fileStats = {
    total: input.files.length,
    available: input.files.filter((file) => file.available).length,
    fetched: filesFetched,
    fetch_errors: fetchErrors.length,
    provider_total: input.files.reduce((sum, file) => sum + file.providers, 0),
  };
  const pipeStats = {
    total: input.pipes.length,
    open: input.pipes.filter((pipe) => pipe.state === 'open').length,
    connected: input.pipes.filter((pipe) => pipe.connected).length,
  };

  const lines = [
    '# Jeliya Diagnostics',
    '',
    'Generated by the Jeliya UI for support. This excludes message bodies, invite tickets, full local paths, file names, pipe targets, and full identity IDs.',
    '',
    '## Runtime',
    `- generated_at: ${input.generatedAt}`,
    `- ui_version: ${input.uiVersion}`,
    `- daemon_version: ${input.status?.version ?? 'unknown'}`,
    `- daemon_mode: ${input.status?.mode ?? 'unknown'}`,
    `- connection: ${input.connection}`,
    `- transport: ${redact(input.transport)}`,
    `- browser: ${redact(input.browser)}`,
    `- platform: ${redact(input.platform)}`,
    '',
    '## Local Node',
    `- identity_present: ${input.status?.identity ? 'yes' : 'no'}`,
    `- identity_id: ${shortOrNone(input.status?.identity?.identity_id)}`,
    `- device_id: ${shortOrNone(input.status?.identity?.device_id)}`,
    `- endpoint_present: ${input.status?.endpoint ? 'yes' : 'no'}`,
    `- endpoint_id: ${shortOrNone(input.status?.endpoint?.endpoint_id)}`,
    `- endpoint_address_present: ${input.status?.endpoint?.addr ? 'yes' : 'no'}`,
    `- relay_url_present: ${input.status?.endpoint?.relay_url ? 'yes' : 'no'}`,
    `- rooms_open_count: ${input.status?.rooms_open.length ?? 0}`,
    '',
    '## Rooms',
    `- total: ${input.rooms.length}`,
    `- open: ${input.rooms.filter((room) => room.open).length}`,
    `- status_counts: ${countRecordValues(countBy(input.rooms, (room) => room.status ?? 'active'))}`,
    `- current_room_id: ${shortOrNone(input.currentRoomId)}`,
    `- current_room_status: ${current?.status ?? 'none'}`,
    `- current_room_open: ${current?.open ? 'yes' : 'no'}`,
    '',
    '## Current Room',
    `- members: ${input.members.length}`,
    `- member_status_counts: ${countRecordValues(countBy(input.members, (member) => member.status))}`,
    `- member_role_counts: ${countRecordValues(countBy(input.members, (member) => member.role))}`,
    `- peers: ${input.peers.length}`,
    `- peer_state_counts: ${countRecordValues(countBy(input.peers, (peer) => peer.state))}`,
    `- peer_path_counts: ${countRecordValues(countBy(input.peers, (peer) => peer.path ?? 'unknown'))}`,
    `- peer_identity_bound_count: ${input.peers.filter((peer) => peer.identity_id).length}`,
    `- files_total: ${fileStats.total}`,
    `- files_available: ${fileStats.available}`,
    `- files_fetched: ${fileStats.fetched}`,
    `- files_fetch_errors: ${fileStats.fetch_errors}`,
    `- files_provider_total: ${fileStats.provider_total}`,
    `- fetch_phase_counts: ${countRecordValues(fetchPhases)}`,
    `- pipes_total: ${pipeStats.total}`,
    `- pipes_open: ${pipeStats.open}`,
    `- pipes_connected: ${pipeStats.connected}`,
  ];

  if (fetchErrors.length > 0) {
    lines.push(`- fetch_error_codes: ${countRecordValues(countBy(fetchErrors, (code) => code))}`);
  }

  lines.push('', '## Last UI Error');
  if (input.lastError) {
    lines.push(
      `- at: ${input.lastError.at}`,
      `- context: ${redact(input.lastError.context)}`,
      `- code: ${redact(input.lastError.code)}`,
      `- message: ${redact(input.lastError.message)}`,
      `- hint: ${input.lastError.hint ? redact(input.lastError.hint) : 'none'}`,
    );
  } else {
    lines.push('- none_captured: yes');
  }

  return `${lines.join('\n')}\n`;
}
